[variables]
NODE_ENV = "production"
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "cd Backend && npm ci",
  "python -m pip install --user -r requirements.txt",
  "python -m playwright install --with-deps chromium"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"